language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
script:
  - cd djangobucketlist && python manage.py test
after_success:
  - coveralls
