# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 11:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BucketList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='modified_on')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bucketlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_modified'],
                'abstract': False,
                'db_table': 'bucketlist',
            },
        ),
        migrations.CreateModel(
            name='BucketListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='modified_on')),
                ('done', models.BooleanField(default=False)),
                ('bucketlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bucketlist.BucketList')),
            ],
            options={
                'ordering': ['done'],
                'abstract': False,
                'db_table': 'bucketlistitem',
            },
        ),
    ]
