# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 20:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bucketlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bucketlistitem',
            options={'ordering': ['done', '-date_modified']},
        ),
    ]
